name: Try CI from joe
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4              # 检出代码
      - uses: actions/setup-node@v4            # 配置 Node.js
        with:
          node-version: 20
      - run: npm ci && npm test               # 安装依赖并测试
        working-directory: ${{ github.workspace }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4       # 保存测试报告
        with:
          name: test-results
          path: ./test-output/